version: "3"

services:
  api:
    container_name: chocolate-api
    restart: always
    build: ./api
    expose:
      - "5000"
    command: python estimationService.py

  nginx:
    container_name: chocolate-nginx
    restart: always
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - api